#! /bin/bash
###############################################
##
##  Copyright (2019, ) Institute of Software
##      Chinese Academy of Sciences
##          wuheng@otcaixiscas.ac.cn
##         wuyuewen@otcaix.iscas.ac.cn
##              2019-9-24
##
###############################################

version="1.17.4"
podcidr="10.244.0.0/16"

function init-env()
{
  swapoff -a
 
  \cp /kubeos/config /etc/selinux/config
 
  systemctl stop firewalld
  systemctl disable firewalld

  res=$(cat /etc/sysctl.conf | grep swappiness)
  sysctl net.bridge.bridge-nf-call-iptables=1
  if [[ -z $res ]]
  then
    echo "vm.swappiness = 0">> /etc/sysctl.conf
  fi
  echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables
  echo "1" > /proc/sys/net/ipv4/ip_forward >/dev/null

  systemctl enable kubelet
  systemctl start kubelet
}

function init-master()
{
  yum install -y docker-ce-19.03.5 docker-ce-cli-19.03.5 kubeadm-$version kubectl-$version kubelet-$version
  systemctl enable docker
  systemctl start  docker
}

function init-node()
{
  yum install -y docker-ce-19.03.5 docker-ce-cli-19.03.5 kubeadm-$version kubectl-$version kubelet-$version
  systemctl enable docker
  systemctl start  docker
}

function setup-master()
{

}

function setup-node()
{
}

function cmddesc()
{
  echo -e "Welcome to kubevirt-ctl, the install plugin for Kubernetes."
  echo -e "kubevirt-ctl: missing command name (use --help for help)\n"
}


function help()
{
  cmddesc
  echo -e "Commands:"
  echo -e "  init-master   :\t(Init) : Install softwares for Kubernetes Master"
  echo -e "  init-node     :\t(Init) : Install softwares for Kubernetes Node"
  echo -e "  setup-master  :\t(Setup): Install Kubernetes Master"
  echo -e "  setup-node    :\t(Setup): Install Kubernetes Node"
}


case $1 in
  "init-master")
    init-master $*
    ;;
  "init-node")
    init-node $*
    ;;
  "setup-master")
    setup-master $*
    ;;
  "setup-node")
    setup-node $*
    ;;
  "--help")
    help
    ;;
  *)
  help
  ;;
esac
