apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-register
  namespace: kube-system
  labels:
    app: docker-register
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-register
  template:
    metadata:
      labels:
        app: docker-register
    spec:
      hostNetwork: true
      containers:
      - image: registry.cn-beijing.aliyuncs.com/cloudplus-mirror/distribution:v2.7.1-amd64
        imagePullPolicy: IfNotPresent
        name: docker-register
        volumeMounts:
           - name: data
             mountPath: /var/lib/registry
      volumes:
      - name: data
        hostPath:
          path: /var/lib/registry
