kind: Service
apiVersion: v1
metadata:
  name: solo-service
  namespace: default
spec:
  selector:
    app: solo-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 8080

