apiVersion: indeed.com/v1alpha1
kind: RabbitMQCustomResource
metadata:
  name: rabbitmq-instance
spec:
  rabbitMQImage: "rabbitmq:3.8.2-management"
  initContainerImage: "busybox:latest"
  createLoadBalancer: true
  replicas: 1
  compute:
    cpuRequest: "1300m"
    memory: "2Gi"
  storage:
    storageClassName: local-storage
    limit: "1Gi"
  clusterSpec:
    highWatermarkFraction: 0.4
    policies:
      - name: "mypolicy"
        vhost: "/"
        pattern: ".*"
        applyTo: "queues"
        definition:
          ha-mode: "exactly"
          ha-params: 2
          ha-sync-mode: "automatic"
    operatorPolicies:
      - name: "myoperatorpolicy"
        vhost: "/"
        pattern: ".*"
        applyTo: "queues"
        definition:
          max-length: 1000
    shovels:
      - name: "myshovel"
        source:
          queue: "myqueue"
          vhost: "/"
        destination:
          addresses:
            - address: "myrabbitmq-svc" # shovel messages from this cluster to itself
              vhost: "/"
          secretName: "mynewadmin-myrabbitmq-user-secret" # user created below
          secretNamespace: "default"
    users:
      - username: "admin"
        tags:
          - "administrator"
        vhosts:
          - vhostName: "/"
            permissions:
              configure: ".*"
              write: ".*"
              read: ".*"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local: 
    path: /data/vol1  
  nodeAffinity: 
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ali3
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-storage-rabbitmq-instance-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
