apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: kube-system
  labels: 
    name: adminer
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: adminer-port
    nodePort: 32080
  selector:
    name: adminer
