apiVersion: v1
kind: ReplicationController
metadata:
  name: adminer
  labels:
    name: adminer
spec:
  replicas: 1
  selector:
    name: adminer
  template:
    metadata:
      labels: 
        name: adminer
    spec:
      containers:
      - name: adminer
        image: adminer:4.7.6-standalone
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
