apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kube-system
  labels: 
    name: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    name: mysql-port
    nodePort: 32306
  selector:
    name: mysql
